### ISSUE TITLE
QC update checklist

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirSensor#215]
Jon's current cleanup of the QC code leaves a variety of items unfinished:

- [x] `pat_downloadParseData()` -- use CSV from ThingSpeak and correct fields using metadata from PurpleAir
- [x] make sure we're using the correct PM25 field
- [x] `pat_externalFit()` -- QC_FUN argument
- [ ] `pat_monitorcomparision()` -- QC_FUN argument
- [x] review and test, review and test
- [x] complete examples for everything through `pat_createAirSensor()`
- [x] test all `PurpleAirSoH_~()` functions
- [x] test `pat_createAirSensor()` with custom FUN
